### ISSUE TITLE
Error in Jenkins build

### ISSUE THREAD

**Issue by AsheemMainaly** [redhat-cop/openshift-applier#103]
```
cd .openshift-applier
+ ansible-galaxy install -r requirements.yml --roles-path=roles
 [WARNING]: - openshift-applier was NOT installed successfully: - command git
checkout v3.9.0 failed in directory /tmp/tmpVaAg6T (rc=1)
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by alberttwong** [comment]
This is affecting a customer.   @sherl0cks @etsauer Can you guys help?

**Comment by oybed** [comment]
@alberttwong @AsheemMainaly the `v3.9.x` tags are super old and also removed per issue https://github.com/redhat-cop/openshift-applier/issues/67. Please update to use the later/newer releases/tags - i.e.: [v2.0.x](https://github.com/redhat-cop/openshift-applier/releases).
