### ISSUE TITLE
Thread safety error on macOS

### ISSUE THREAD

**Issue by jacobsee** [redhat-cop/openshift-applier#121]
During the step `Determine location for the file`, the following error is thrown:
```
TASK [openshift-applier/roles/openshift-applier : Determine location for the file] ***
objc[850]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[850]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
I have observed this on three Macs so far.

The quick workaround is to set the environment variable
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

...but we should probably come up with a better solution.

**Comment by tylerauerbeck** [comment]
@jacobsee So I've seen this a bunch and the answer on the Ansible issues I've seen are "this isn't our problem, this is Apple's doing". Specifically they made a choice on thread safety with the version of python that they're distributing. Not sure that there's anything that we can do if Ansible doesn't want to do anything either.

For reference: https://github.com/ansible/ansible/issues/32499

**Comment by jacobsee** [comment]
Sad trombone. Okay.
