### ISSUE TITLE
Consider A Different Docker Command For Image

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/openshift-applier#19]
The image uses sleep infinity, so if I user forgets to supply a command when running the container, they an unresponsive container that hangs and needs to be killed via `docker rm` or the like. Replacing with `/bin/bash` seems to be a bit more user friendly.

Thoughts?

**Comment by sabre1041** [comment]
@sherl0cks can we close this? Command has been updated and no longer uses _sleep_
