### ISSUE TITLE
Create tags as well as labels in the applier

### ISSUE THREAD

**Issue by springdo** [redhat-cop/openshift-applier#26]
I want to be able to tag images from different namespace and create labels on that new is in my given project. @oybed this links to https://github.com/rht-labs/enablement-docs/issues/236 as discussed there.

**Comment by oybed** [comment]
This should be modelled after one of the "supporting" roles that can be used as a post-step to tag images.

**Comment by oybed** [comment]
This has been moved to https://github.com/redhat-cop/casl-ansible as that's where these roles now are.

Ref issue:
https://github.com/redhat-cop/casl-ansible/issues/273
