### ISSUE TITLE
template param required

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/openshift-applier#40]
I have ran into [params file doesn't exist](https://github.com/redhat-cop/openshift-applier/blob/master/roles/openshift-applier/tasks/process-template.yml#L15) a couple of times. I have built my own Jenkins image which does not require a param file to be used when applying the template. What is the recommended approach to this solution? I just created an empty param file with a comment.

**Comment by oybed** [comment]
@Gl4di4torRr with the newest release https://github.com/redhat-cop/openshift-applier/releases/tag/v2.0.0, the `openshift-applier` no longer requires that params file to be there - i.e.: if the template has all default values, etc. etc. Please give the latest version a try to see if that meet your needs.

**Comment by Gl4di4torRr** [comment]
@oybed that will work! thanks

**Comment by oybed** [comment]
Great - closing out this for now. Please re-open if you find any issues for this with `v2.0.0`.
