### ISSUE TITLE
separate out the role into its own repository so it can be included in a requirements file

### ISSUE THREAD

**Issue by itewk** [redhat-cop/openshift-applier#62]
I want to be able to re-use the key role from this project in other projects so I can have custom playbooks, vaults, etc but I can't easily do that today because a requirements file requires the role to be the top level element in a repository.

**Comment by itewk** [comment]
@oybed @etsauer I hear you two are the two to talk to about this :)

**Comment by etsauer** [comment]
@itewk we use requirements files to include applier in other projects all the time. The main difference is that you need to adjust your role paths to something like:

```
---
- hosts: applier-hosts[0]
  roles:
    - galaxy-deps/openshift-applier/roles/openshift-applier
```

. The reason that we DON'T split out our roles into separate repos is that the redhat-cop github org is already exploding and becoming kind of hard to manage, and until GitHub support something like subgroups, we're concerned about the maintenance overhead of all of the repos that would be created.

**Comment by oybed** [comment]
@etsauer explained it well, and just to add a few more pieces of info: The `openshift-applier` repo was created as a "standalone" repo just for this purpose that you are asking about - i.e.: a repo that can be kept lean and simple that can be used with galaxy to pull in the openshift-applier without getting the "whole world" at the same time. I do wish that the galaxy tooling had the option to filter just a portion of a repo, but that's a git/galaxy limitation that we just have to live with.

For a few examples of where the `openshift-applier` is being used a galaxy dependency, please check out these repos:
https://github.com/redhat-cop/casl-ansible/blob/master/casl-requirements.yml#L9-L11
https://github.com/rht-labs/labs-ci-cd/blob/master/requirements.yml#L4-L8

**Comment by itewk** [comment]
@etsauer @oybed thank you for the examples, I didn't know you could path like that when doing a role.
