### ISSUE TITLE
openshift-applier doesn't support ConfigMaps

### ISSUE THREAD

**Issue by AndresAbdo** [redhat-cop/openshift-applier#75]
Does it make sense for the openshift-applier to support configmaps?

**Comment by oybed** [comment]
@AndresAbdo the `openshift-applier` itself doesn't get involved with what's in the static, or template, files used with OpenShift, so you can easily have a `ConfigMap` in your files and apply it with the `openshift-applier`. Hope that make sense.

**Comment by oybed** [comment]
@rohanmars the openshift-applier does **NOT** do anything special for projects, deployments and builds. In fact, the openshift-applier is very very little hands on with anything as all it does is to process static files or templates with content... the content of these files can be any of the above, or a ConfigMap definition. 

Please have a look at the sample inventories in the `tests` area for some examples if you haven't already looked. Also, in case I'm just misunderstanding your question, please elaborate on what kind of functionality you have seen for the above that you are wanting the ConfigMap to follow + provide an example of it.

**Comment by jibbe** [comment]
@oybed, this is what I want todo within a seed-hosts.yml:

openshift_cluster_content:
- object: configmap
  content:
  - name: "apply configuration"
    file: "{{ inventory_dir }}/../.openshift/config/dev-config.yml"

**Comment by oybed** [comment]
@jibbe yes, and you can do that as-is.  Have you tried it?

**Comment by rohanmars** [comment]
I tried it, doesn't work.

**Comment by oybed** [comment]
@jibbe @rohanmars I think maybe the main concept of the `openshift-applier` isn't understood here. The `openshift-applier` just takes a collection of files and process/apply them (or create). In essence, it would be like if you did these steps manually:
```
oc process -f file1.yml --params-file=param1 | oc apply -f -
oc process -f file2.yml --params-file=param2 | oc apply -f -
oc process -f file3.yml --params-file=param3 | oc apply -f -
oc create -f file4.yml
oc process -f file5.yml --params-file=param5 | oc apply -f -
```

But instead of doing these 5 steps manually (or through a bash script), it can be specified in an inventory which the openshift-applier iterates through and perform the process/apply or create. Hence, the openshift-applier does **not** have any knowledge itself around ConfigMaps, BuildConfigurations, Routes, etc. etc. It's pretty much as dumb as it can be and just loops over what you give it.

**Comment by rohanmars** [comment]
@oybed yes, that was our assumption.  We'll try an figure out why it didn't work. Unfortunately, you can't run a "oc process" on a configmap so not sure that makes sense.

**Comment by oybed** [comment]
@rohanmars @jibbe in case it helps, here's a quick example I just put together for ConfigMaps. This shows both a static ConfigMap as well as a template based ConfigMap:

Inventory:
```
openshift_cluster_content:
- object: configmap
  content:
  - name: "Create ConfigMap1"
    file: "{{ inventory_dir }}/../files/configmap1.yml"
    action: "create"
  - name: "Apply ConfigMap2"
    template: "{{ inventory_dir }}/../files/configmap2.yml"
    params: "{{ inventory_dir }}/../files/params2"
```

Files:
```
$ cat files/configmap1.yml 
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: map1
data: 
  foo1: bar1

$ cat files/configmap2.yml 
---
apiVersion: v1
kind: Template
metadata:
  name: ConfigMap-Example
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: map2
  data: 
    foo1: "${VALUE}"
parameters:
- name: "VALUE"
  displayName: "The Value"

$ cat files/params2 
VALUE=file-value-2
```

Post `openshift-applier` run:

```
> oc get configmap
NAME      DATA      AGE
map1      1         5m
map2      1         3m

>oc get configmap map1 -o yaml | grep -A1 '^data:'
data:
  foo1: bar1

> oc get configmap map2 -o yaml | grep -A1 '^data:'
data:
  foo1: file-value-2
```

**Comment by oybed** [comment]
Note the `action: create` on the static file - as documented here: https://github.com/redhat-cop/openshift-applier/blob/master/roles/openshift-applier/README.md#override-default-actions-with-action

**Comment by rohanmars** [comment]
Okay great @oybed . We'll try that, I think the "action: create" was the missing piece.

Thanks.

**Comment by oybed** [comment]
The `create` shouldn't be needed (I've successfully run without it), but it is good to know about in case you need to do such an override. `apply` is the default, but in some rare cases it cannot be used (e.g.: ProjectRequest). For ConfigMaps, however, you should be able to just leave it at default `apply`.
