### ISSUE TITLE
not able run from control machine - not all objects applied successfully -  ex. object with param file 

### ISSUE THREAD

**Issue by rajmechi** [redhat-cop/openshift-applier#89]
it's confusing to find the latest tag. it seems v2.0.5 is newer than v3.9.1.
and v2.0.5  is working as i expected.

**Comment by rajmechi** [comment]
https://github.com/redhat-cop/openshift-applier/blob/v3.9.1/roles/openshift-applier/tasks/process-one-entry.yml


we tried run applier from tower but we found current galaxy role ( latest tag v3.9.1) not supported - run playbook on local but execute remorely - ( i made few changes to work )
modified  galaxy/openshift-applier/roles/openshift-applier/tasks/process-one-entry.yml
  
  - name: "{{ template_action | capitalize }} OpenShift objects based on template with params for '{{ entry.object}} : {{ content.name | default(template | basename) }}'"
  shell: >
    oc process \
      {{ process_local }} \
      {{ template_f_option }} {{ template }} \
      {{ target_namespace }} \
      --param-file={{ tmp_inv_dir }}{{ item }} | \
    oc {{ template_action }} {{ target_namespace }} -f - {{ (template_action == 'delete') | ternary(' --ignore-not-found', '') }}
  register: command_result
  failed_when:
  - command_result.rc != 0
  - "'AlreadyExists' not in command_result.stderr"
  with_fileglob:
  - "{{ content.params }}/*"
  #- "{{ tmp_inv_dir }}{{ content.params }}/*"  commented this line and added above line

**Comment by oybed** [comment]
@rajmechi please make sure to check the release notes for the releases. You'll see the `v3.9.x` release have been "replaced" - i.e.:
https://github.com/redhat-cop/openshift-applier/releases/tag/v3.9.1

**Comment by oybed** [comment]
@rajmechi did you get a chance to try one of the latest releases? I'd recommend giving `v2.0.6` a try and report back if you are seeing the same issues with that release.

**Comment by oybed** [comment]
@rajmechi per you first post , you had it working with `v2.0.5`. Since I haven't heard anything back in awhile, I'll take this as it is working and will be closing out this issue. Please re-open with additional info if you feel so.
