### ISSUE TITLE
Molecule should test on multiple versions of Ansible & Python

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-applier#99]
Thinking at a minimum, we need:
- Ansible 2.6 on Python 2
- Ansible 2.7 on Python 2
- Ansible 2.6 on Python 3
- Ansible 2.7 on Python 3

**Comment by oybed** [comment]
somewhat related is this issue: https://github.com/redhat-cop/openshift-applier/issues/85

**Comment by tylerauerbeck** [comment]
Resolved by #107
